# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-19 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categroy',
            field=models.CharField(blank=True, default='\u540e\u7aef\u5f00\u53d1', max_length=30, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
    ]
