# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-20 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_categroy'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=20, verbose_name='\u76f8\u5173\u8bfe\u7a0b\u6807\u7b7e'),
        ),
    ]
